# Generated by Django 4.0.3 on 2023-05-23 13:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_post_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='watchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
