# Generated by Django 4.0.3 on 2023-05-30 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_comment_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='content',
        ),
    ]
